## Pandas (High-Perf, Easy to use data structures n analysis tools for python)

## DataFrame and DataSeries

In [1]:
import pandas as pd
import numpy as np

In [58]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5']
                ,columns=['Column1','Column2','Column3','Column4'])
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [56]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

## Data Frame common ops

In [62]:
df[['Column2','Column3']]

Column2  Column3
Row1        1        2
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

In [64]:
df.loc[['Row1','Row4']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row4       12       13       14       15

In [11]:
# exports the above data frame to xls format/any format to the drive.
df.to_excel('C:\\Users\\prathap\\Desktop\\Pandas_DataFrameTestExcel1.xls')

In [32]:
# accessing the elements from the tabular data..
# accessing rows
print(df.loc['Row2'])
print('----------------------------------------return type is data series for df.loc')
print(type(df.loc['Row2']))
print('Series is basically either one row or one column data')
# accessing cols
print('----------------------------------------similar to numpy or sets/lists df.iloc[:,:]')
print(df.iloc[:,:])
print('----------------------------------------similar to numpy or sets/lists df.iloc[0:2,1:3]')
print(df.iloc[0:2,1:3])
print('----------------------------------------similar to numpy or sets/lists df.iloc[:2,2:]')
print(df.iloc[:2,2:])
print('----------------------------------------return type is data frame for df.iloc')
print(type(df.iloc[:,:]))
#print(df.iloc['Row2':'Column2'])

Column1    4
Column2    5
Column3    6
Column4    7
Name: Row2, dtype: int32
----------------------------------------return type is data series for df.loc
<class 'pandas.core.series.Series'>
Series is basically either one row or one column data
----------------------------------------similar to numpy or sets/lists df.iloc[:,:]
      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
----------------------------------------similar to numpy or sets/lists df.iloc[0:2,1:3]
      Column2  Column3
Row1        1        2
Row2        5        6
----------------------------------------similar to numpy or sets/lists df.iloc[:2,2:]
      Column3  Column4
Row1        2        3
Row2        6        7
----------------------------------------return type is data frame for  for df.iloc
<class 'pandas.core.frame.Data

In [39]:
# convert data frames to array
print('-------------------Converts the data frame to array----------------df.iloc[:,:].values')
print(df.iloc[:,:].values)
print('----------------indexing again--------------')
print(df.iloc[:,:].values[1:2,:3])


-------------------Converts the data frame to array----------------df.iloc[:,:].values
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
----------------indexing again--------------
[[4 5 6]]


In [51]:
print(df.isnull())
print(df.isnull().sum())
print(df.head())

      Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False
Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64
      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


In [50]:
print(df.isin([2,4,6]))
print(df.isin([2,4,6]).sum())

      Column1  Column2  Column3  Column4
Row1    False    False     True    False
Row2     True    False     True    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False
Column1    1
Column2    0
Column3    2
Column4    0
dtype: int64


In [65]:
df['Column2'].value_counts() # provides count of repetetive values..(duplicates)

13    1
5     1
17    1
9     1
1     1
Name: Column2, dtype: int64

In [66]:
df['Column2'].unique() # return all unique values..(non-duplicates)

array([ 1,  5,  9, 13, 17], dtype=int64)

In [67]:
df.isna()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [70]:
df.Column1

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [69]:
df["Column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [72]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [71]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000